version: '3.8'

services:
  peixun-app:
    build: .
    container_name: peixun-service
    ports:
      - "8001:8000" # 避开原项目占用的 8000 端口，映射到服务器的 8001 端口
    volumes:
      - ./uploads:/app/uploads # 挂载图片目录，容器升级重建不丢失照片
      - ./static:/app/static   # 挂载静态网页目录，后续 git pull 静态 HTML 可热生效，无需重新构建容器
      # 挂载 SQLite 数据库文件，防止容器重建时数据丢失
      - ./peixun.db:/app/peixun.db
    restart: always
